Ahoo-Wang/fetcher

- packages/fetcher/README.md
- packages/fetcher/README.zh-CN.md
- packages/fetcher/src/fetcher.ts
- packages/fetcher/src/fetcherRegistrar.ts
- packages/fetcher/src/index.ts
- packages/fetcher/src/namedFetcher.ts
- packages/fetcher/src/timeout.ts
- packages/fetcher/src/types.ts
- packages/fetcher/test/namedFetcher.test.ts
- Add NamedFetcher class to allow automatic registration with global fetcherRegistrar
- Update index.ts to include new namedFetcher module
- Create namedFetcher.ts file with NamedFetcher implementation
- Add NamedCapable interface in types.ts
- Write unit tests for NamedFetcher in namedFetcher.test.ts
- Update README.md and README.zh-CN.md with NamedFetcher usage examples and documentation
> feat(fetcher): implement NamedFetcher and update related documentation

- scripts/init.sh
- Add pnpm format and pnpm lint commands to the init script
- Ensures codebase is properly formatted and linted during initialization
> ci(init): add formatting and linting steps to init script

- packages/fetcher/README.md
- packages/fetcher/README.zh-CN.md
- packages/fetcher/src/namedFetcher.ts
- packages/fetcher/src/types.ts
- packages/fetcher/test/namedFetcher.test.ts
- scripts/init.sh
- Add a default NamedFetcher instance named 'default' that is automatically registered
- Update namedFetcher.ts to export the default fetcher and its name
- Modify test to include checks for the default fetcher
- Update README files with information on how to use the default fetcher
> feat(fetcher): export a default named fetcher instance 

- README.md
- README.zh-CN.md
- packages/fetcher/README.md
- packages/fetcher/README.zh-CN.md
- packages/fetcher/src/namedFetcher.ts
- packages/fetcher/src/types.ts
- packages/fetcher/test/namedFetcher.test.ts
- scripts/init.sh
- Added sections in both English and Chinese README files
- Provided example code for using the default Fetcher instance
- Improved documentation for the Fetcher library usage
> docs(README): add information about using the default Fetcher 

- packages/cosec/tsconfig.json
- packages/eventstream/tsconfig.json
- packages/fetcher/tsconfig.json
- Update include pattern to "src/**/*" in all three tsconfig.json files
- Update exclude pattern to only "node_modules" and "dist" in all three tsconfig.json files
- Remove "test" from exclude pattern and add "test/**/*" to include pattern
> build(tsconfig): update include/exclude patterns for tsconfig.json files

- README.md
- examples/package.json
- package.json
- packages/cosec/package.json
- packages/decorator/package.json
- packages/eventstream/package.json
- packages/fetcher/package.json
- scripts/update-all-versions.sh
- Add update-all-versions.sh script to simplify version updates across all packages
- Increment version to 0.5.3 in all package.json files
- Update README with instructions for using the new version update command
> build: add version update script and increment version

- README.md
- README.zh-CN.md
- packages/cosec/package.json
- packages/decorator/package.json
- packages/eventstream/package.json
- packages/fetcher/README.md
- packages/fetcher/README.zh-CN.md
- packages/fetcher/package.json
- Update README.md and README.zh-CN.md with more detailed feature descriptions
- Update package.json descriptions for cosec, decorator, eventstream, and fetcher packages
- Refactor README structure to highlight individual packages and their features
- Add new features to the list, including named fetcher support and default fetcher instance
> docs: update README and package descriptions

- packages/fetcher/src/fetcher.ts
- Update FetcherRequest interface to extend HeadersCapable
- Remove 'headers' from Omit type in FetcherRequest
> refactor(fetcher): update FetcherRequest interface to extend HeadersCapable

- packages/decorator/src/requestExecutor.ts
- packages/decorator/test/apiDecorator.test.ts
- packages/decorator/test/endpointDecorator.test.ts
- packages/decorator/test/requestExecutor.branch.test.ts
- packages/decorator/test/requestExecutor.test.ts
- packages/fetcher/src/fetcher.ts
- pnpm-lock.yaml
- Add signal property to the request object
- Implement logic to handle AbortSignal in request parameters
- Update tests to cover new functionality
> feat(decorator): add support for AbortSignal in requests

- examples/package.json
- package.json
- packages/cosec/package.json
- packages/decorator/package.json
- packages/eventstream/package.json
- packages/fetcher/package.json
- Update version in package.json files for fetcher, examples, cosec, decorator, eventstream, and root
> build: bump version to 0.5.8

- examples/package.json
- examples/src/interceptorExample.ts
- package.json
- packages/cosec/package.json
- packages/cosec/src/cosecRequestInterceptor.ts
- packages/cosec/src/cosecResponseInterceptor.ts
- packages/decorator/package.json
- packages/eventstream/package.json
- packages/eventstream/src/eventStreamInterceptor.ts
- packages/fetcher/README.md
- packages/fetcher/package.json
- packages/fetcher/src/index.ts
- packages/fetcher/src/interceptor.ts
- packages/fetcher/src/orderedCapable.ts
- packages/fetcher/src/requestBodyInterceptor.ts
- packages/fetcher/src/types.ts
- packages/fetcher/test/fetcher-interceptor.test.ts
- packages/fetcher/test/interceptor.test.ts
- packages/fetcher/test/orderedCapable.test.ts
- Add OrderedCapable interface to control execution order of interceptors
- Implement toSorted function for sorting ordered capable items
- Update InterceptorManager to use ordered intercepters
- Add tests for ordered interceptor functionality
- Update documentation to cover new interceptor ordering system
> feat(fetcher): implement ordered interceptor system

- packages/decorator/src/reflection.ts
- packages/decorator/test/reflection.test.ts
- Add a cache to store previously extracted parameter names
- Check cache before extracting parameter names to improve performance
- Update tests to verify caching behavior
> perf(decorator): implement caching for function parameter names

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/release.yml
- Create release.yml to automate release process and generate changelog
- Define categories for changelog entries based on issue labels
- Include all relevant labels for categorizing changes
- Set up exclusion for irrelevant labels
> ci: add release configuration file

- packages/fetcher/src/fetcher.ts
- Enhance code formatting for better readability
- Add detailed JSDoc comment for the new exchange function
- Update variable names for consistency throughout the fetch process
> refactor(fetcher): improve code readability and add exchange function documentation

- packages/fetcher/src/fetchExchange.ts
- packages/fetcher/src/fetcher.ts
- packages/fetcher/src/mergeRequest.ts
- Move FetcherRequest interface from fetcher.ts to fetchExchange.ts
- Update import statements in fetcher.ts and mergeRequest.ts
- This change prepares for implementing a new RequestFactory class
> refactor(fetcher): move FetcherRequest interface to fetchExchange.ts

- eslint.config.js
- packages/fetcher/README.md
- packages/fetcher/src/fetcher.ts
- packages/fetcher/src/index.ts
- packages/fetcher/src/interceptor.ts
- packages/fetcher/src/requestBodyInterceptor.ts
- packages/fetcher/src/urlBuilder.ts
- packages/fetcher/src/urlResolveInterceptor.ts
- packages/fetcher/test/fetcher-exchange.test.ts
- packages/fetcher/test/fetcherInterceptors.test.ts
- packages/fetcher/test/requestBodyInterceptor.test.ts
- packages/fetcher/test/urlResolveInterceptor.test.ts
- Add UrlResolveInterceptor to handle URL resolution before other interceptors
- Update Fetcher to use the new UrlResolveInterceptor
- Modify the interceptor chain order to ensure proper execution sequence
- Add tests for UrlResolveInterceptor and updated interceptor chain
> feat(fetcher): implement UrlResolveInterceptor for early URL resolution

- packages/cosec/src/cosecRequestInterceptor.ts
- packages/cosec/src/cosecResponseInterceptor.ts
- packages/eventstream/src/eventStreamInterceptor.ts
- Add detailed JSDoc comments for CoSecRequestInterceptor and CoSecResponseInterceptor
- Improve EventStreamInterceptor documentation with example usage
- Remove redundant class description comments
> docs(interceptors): enhance API documentation for interceptors

- packages/fetcher/src/urlBuilder.ts
- packages/fetcher/src/utils.ts
- packages/fetcher/test/urlBuilder.test.ts
- packages/fetcher/test/utils.test.ts
- Add detailed JSDoc comments for UrlBuilder class and methods
- Enhance URLBuilder interface and functionality
- Add comprehensive unit tests for UrlBuilder
- Implement and test mergeRecords utility function
> docs(fetcher): improve URLBuilder documentation and testing

- packages/fetcher/src/fetchRequest.ts
- Add BaseURLCapable interface for objects with baseURL property
- Improve documentation for HttpMethod enum and RequestHeaders interface
- Add RequestHeadersCapable interface for objects with headers property
- Add FetchRequest interface extending FetchRequestInit with required URL
> refactor(fetcher): add type interfaces and improve documentation

- packages/wow/src/query/queryable.ts
- Add optional fields for pagination and limit in query interfaces
- Include type descriptions for better code documentation
- Define a default projection constant
- Make projection optional in ProjectionCapable interface
> refactor(query): make pagination and limit optional in query interfaces

- packages/eventstream/src/eventStreamInterceptor.ts
- Simplify the condition for checking content type using optional chaining
- Remove unnecessary comment for code clarity
> refactor(eventstream): improve content type checking for event streams

- packages/fetcher/src/fetchExchange.ts
- packages/fetcher/src/fetcher.ts
- packages/fetcher/src/fetcherError.ts
- packages/fetcher/src/index.ts
- packages/fetcher/src/timeout.ts
- packages/fetcher/test/fetchExchange.test.ts
- packages/fetcher/test/fetcherError.comprehensive.test.ts
- packages/fetcher/test/fetcherError.test.ts
• Refactored error handling: Moved error classes to a separate fetcherError.ts file for better organization
• Enhanced error classes: Added comprehensive error handling with better inheritance and error information
• Improved test coverage: Added extensive tests for all error classes with 100% coverage
• Fixed fetch error handling: Updated fetch method to use custom FetchError instead of generic Error
1. Created new fetcherError.ts with FetcherError, ExchangeError, FetchError, and FetchTimeoutError classes
2. Moved FetchTimeoutError from timeout.ts to fetcherError.ts
3. Enhanced error classes with better documentation and error chaining support
4. Added comprehensive test suites for all error classes
5. Updated imports and references throughout the codebase
• Better error handling with …
> refactor(fetcher): enhance error handling and improve test coverage

- packages/fetcher/src/index.ts
- packages/fetcher/src/validateStatusInterceptor.ts
- packages/fetcher/test/validateStatusInterceptor.test.ts
- Implement HttpStatusValidationError to handle status validation errors
- Create ValidateStatusInterceptor to intercept and validate response status
- Add default and custom status validation support
- Include unit tests for ValidateStatusInterceptor
> feat(fetcher): add ValidateStatusInterceptor to validate HTTP response status

- packages/cosec/src/cosecRequestInterceptor.ts
- packages/cosec/src/cosecResponseInterceptor.ts
- packages/eventstream/src/eventStreamInterceptor.ts
- packages/fetcher/src/fetchInterceptor.ts
- packages/fetcher/src/requestBodyInterceptor.ts
- packages/fetcher/src/urlResolveInterceptor.ts
- packages/fetcher/src/validateStatusInterceptor.ts
- packages/fetcher/test/fetcherInterceptors.test.ts
- packages/fetcher/test/interceptor.test.ts
- packages/fetcher/test/requestBodyInterceptor.test.ts
- packages/fetcher/test/urlResolveInterceptor.test.ts
- packages/fetcher/test/validateStatusInterceptor.test.ts
- Update CoSecRequestInterceptor order to run after RequestBodyInterceptor
- Adjust CoSecResponseInterceptor order to run earlier
- Modify EventStreamInterceptor order to run slightly earlier
- Update FetchInterceptor order to run slightly earlier
- Adjust RequestBodyInterceptor order to run after UrlResolveInterceptor
- Modify UrlResolveInterceptor order to run earlier
- Update ValidateStatusInterceptor order to run slightly earlier
> refactor(interceptors): adjust interceptor order for better request processing

- packages/fetcher/src/interceptor.ts
- Add detailed TypeScript interfaces for RequestInterceptor, ResponseInterceptor, and ErrorInterceptor
- Include JSDoc comments to explain the purpose and usage of each interceptor type
- Provide examples of how to implement each type of interceptor
> refactor(fetcher): add documentation for Typed interceptors

- packages/fetcher/src/interceptor.ts
- packages/fetcher/src/interceptorManager.ts
- packages/fetcher/test/interceptor.test.ts
- packages/fetcher/test/interceptorManager.test.ts
- Register ValidateStatusInterceptor in the response interceptor registry by default
- Update documentation to reflect the new built-in interceptor
- Improve error handling and status code validation in HTTP requests
> feat(fetcher): add built-in status code validation interceptor

- packages/decorator/package.json
- packages/decorator/src/apiDecorator.ts
- packages/decorator/src/endpointDecorator.ts
- packages/decorator/src/requestExecutor.ts
- packages/decorator/src/resultExtractor.ts
- packages/decorator/test/apiDecorator.test.ts
- packages/decorator/test/resultExtractor.test.ts
- pnpm-lock.yaml
- Introduce ResultExtractor interface for processing fetch exchange results
- Implement JsonResultResultExtractor for extracting JSON data from response
> feat(decorator): add result extractor for fetch exchange

- packages/decorator/package.json
- packages/decorator/src/resultExtractor.ts
- packages/decorator/test/resultExtractor.test.ts
- packages/decorator/vite.config.ts
- pnpm-lock.yaml
- Implement CommandResultEventStreamResultExtractor to handle command result event stream extraction
- Update ResultExtractors to include the new extractor
- Add necessary imports and test coverage for the new functionality
- Modify package.json and pnpm-lock.yaml to include @ahoo-wang/fetcher-wow dependency
> feat(decorator): add CommandResultEventStream result extractor

- packages/decorator/src/index.ts
- packages/decorator/test/resultExtractor.test.ts
- Add resultExtractor module to the decorator package
- Update import path in resultExtractor test to use relative path
> feat(decorator): add resultExtractor module and update related tests

- packages/eventstream/src/eventStreamInterceptor.ts
- packages/eventstream/src/types.ts
- packages/eventstream/test/eventStreamInterceptor.test.ts
- Add jsonEventStream method to Response interface
- Implement toJsonServerSentEventStream in eventStreamInterceptor
- Update types.ts to include JsonServerSentEventStream import and method declaration
> feat(eventstream): add jsonEventStream method to Response

- packages/fetcher/src/fetcher.ts
- Replace mergeRecords function with object spread syntax
- Improve readability and performance of header merging
> refactor(fetcher): update header merging process 

- examples/package.json
- integration-test/package.json
- package.json
- packages/cosec/package.json
- packages/decorator/package.json
- packages/eventstream/package.json
- packages/fetcher/package.json
- packages/wow/package.json
- Update version from 0.11.5 to 1.0.0 in multiple package.json files
- This change affects the following packages:
- @ahoo-wang/fetcher-examples
- @ahoo-wang/fetcher-integration-test
- @ahoo-wang/fetcher-cosec
- @ahoo-wang/fetcher-decorator
- @ahoo-wang/fetcher-eventstream
- @ahoo-wang/fetcher
- @ahoo-wang/fetcher-wow
- fetcher
> build: bump version to 1.0.0

- packages/decorator/README.md
- packages/decorator/README.zh-CN.md
- Added section explaining the priority order for fetcher resolution
- Updated both English and Chinese README files with the new information
- Clarified how the fetcher is determined at different levels (instance, endpoint, class, default)
> docs(decorator): add fetcher resolution priority explanation

- packages/cosec/src/index.ts
- packages/cosec/src/jwts.ts
- packages/cosec/test/jwts.test.ts
- Implement JwtPayload interface for standard JWT claims
- Add parseJwtPayload function to decode and parse JWT tokens
- Include unit tests for JWT parsing functionality
> feat(cosec): add JWT parsing functionality

- packages/wow/src/query/event/domainEventStream.ts
- packages/wow/src/query/event/eventStreamQueryApi.ts
- packages/wow/src/query/event/index.ts
- packages/wow/src/query/snapshot/index.ts
- packages/wow/src/query/snapshot/snapshot.ts
- Add EventStreamQueryApi interface for querying domain event streams
- Move domainEventStream.ts to event subfolder and update imports
- Create new index.ts files for event and snapshot modules
- Update query index.ts to include new event module
> feat(query): add event stream query API and update related modules

- .github/workflows/integration-test.yml
- Add MongoDB service to the integration test workflow
- Set up environment variables for MongoDB connection and configuration
- Update health check options for the wow service
> ci(integration-test): add MongoDB service and configure environment variables

- packages/wow/src/query/snapshot/snapshotQueryApi.ts
- packages/wow/test/query/snapshot/snapshotQueryApi.test.ts
- Add SnapshotQueryEndpointPaths class to define endpoint paths for snapshot query operations
- Create unit tests for SnapshotQueryEndpointPaths to verify correct path values
> feat(query): add snapshot query endpoint paths and unit tests

- packages/wow/src/query/event/eventStreamQueryApi.ts
- packages/wow/test/query/event/eventStreamQueryApi.test.ts
- Add EventStreamQueryEndpointPaths class to define endpoint paths for event stream query operations
- Create unit test for EventStreamQueryEndpointPaths to verify correct path values
> feat(query): add endpoint paths for event stream query and related test

- packages/eventstream/src/eventStreamConverter.ts
- packages/eventstream/src/responses.ts
- packages/eventstream/test/eventStreamConvertError.test.ts
- packages/eventstream/test/eventStreamConverter.test.ts
- packages/eventstream/test/responses.test.ts
- Introduce EventStreamConvertError class to handle conversion errors
- Update error throwing in eventStreamConverter and responses
- Add unit tests for EventStreamConvertError
- Modify existing tests to expect EventStreamConvertError
> feat(eventstream): add custom error class for event stream conversion

- packages/wow/src/command/commandHeaders.ts
- packages/wow/src/command/commandHttpClient.ts
- packages/wow/src/query/event/domainEventStream.ts
- packages/wow/src/query/event/eventStreamQueryApi.ts
- packages/wow/src/query/event/eventStreamQueryClient.ts
- packages/wow/src/query/queryApi.ts
- packages/wow/src/query/snapshot/snapshotQueryApi.ts
- packages/wow/src/query/sort.ts
- packages/wow/src/types/endpoints.ts
- Add type definitions for various interfaces and methods
- Improve JSDoc comments for better code clarity
- Refactor some method implementations for better readability
- Update examples in commandHeaders.ts
> refactor(wow): add type definitions and improve documentation

- integration-test/test/wow/commandClient.test.ts
- integration-test/test/wow/eventStreamQueryClient.test.ts
- integration-test/test/wow/snapshotQueryClient.test.ts
- packages/wow/README.md
- packages/wow/src/command/commandClient.ts
- packages/wow/src/command/commandHttpHeaders.ts
- packages/wow/src/command/commandRequest.ts
- packages/wow/src/command/index.ts
- packages/wow/test/command/commandHeaders.test.ts
- packages/wow/vitest.config.ts
- Rename CommandHttpClient to CommandClient
- Rename CommandHeaders to CommandHttpHeaders
- Rename CommandHttpRequest to CommandRequest
- Update related test files and documentation
> refactor(wow): rename CommandHttpClient to CommandClient and update related files

- packages/wow/README.md
- packages/wow/README.zh-CN.md
- packages/wow/vite.config.ts
- Update README to reflect new CommandClient, SnapshotQueryClient, and EventStreamQueryClient
- Add comprehensive examples for command sending and query operations
- Remove outdated sections and improve overall documentation structure
> docs(wow): update README with new API and examples

- integration-test/src/wow/cart/cartClientOptions.ts
- integration-test/src/wow/cart/cartCommandClient.ts
- integration-test/src/wow/cart/cartEventStreamQueryClient.ts
- integration-test/src/wow/cart/cartSnapshotQueryClient.ts
- integration-test/src/wow/cart/index.ts
- integration-test/src/wow/exampleFetcher.ts
- integration-test/src/wow/index.ts
- integration-test/test/wow/cart/cartCommandClient.test.ts
- integration-test/test/wow/cart/cartEventStreamQueryClient.test.ts
- integration-test/test/wow/cart/cartSnapshotQueryClient.test.ts
- Create dedicated test files for cart command, event stream, and snapshot query clients
- Refactor test setup to use shared cart client options and utilities
- Update test cases to match new client structures and naming conventions
> test(wow): organize cart related test cases

- packages/wow/README.md
- packages/wow/src/command/commandClient.ts
- packages/wow/src/query/event/eventStreamQueryClient.ts
- packages/wow/src/query/snapshot/snapshotQueryClient.ts
- Add detailed examples for CommandClient, SnapshotQueryClient, and EventStreamQueryClient
- Improve documentation for query operations and methods
- Refactor code examples to use more realistic and relatable scenarios
- Update README structure for better readability and organization
> docs(wow): enhance README with more comprehensive examples and documentation

- package.json
- packages/cosec/package.json
- packages/cosec/vite.config.ts
- packages/decorator/package.json
- packages/decorator/vite.config.ts
- packages/eventstream/package.json
- packages/eventstream/vite.config.ts
- packages/fetcher/package.json
- packages/fetcher/vite.config.ts
- packages/wow/package.json
- packages/wow/vite.config.ts
- pnpm-lock.yaml
- Add vite-bundle-analyzer to all packages
- Update package.json to include analyze script
- Modify vite.config.ts to integrate analyzer plugin
> build(deps): add bundle analyzer for performance optimization

- packages/fetcher/src/urlTemplateResolver.ts
- packages/fetcher/test/urlTemplateResolver.test.ts
- Implement UrlTemplateResolver interface for resolving URL templates
- Add UriTemplateResolver class for RFC 6570 compliant URI templates
- Add ExpressUrlTemplateResolver class for Express-style URL templates
- Include unit tests for both resolver implementations
> feat(fetcher): add URL template resolver for URI and Express-style templates

- packages/fetcher/src/urlTemplateResolver.ts
- packages/fetcher/test/urlTemplateResolver.test.ts
- Introduce UrlTemplatePathStyle enum to define supported path styles
- Implement getUrlTemplateResolver factory function for style-specific resolvers
- Add tests for new URL template path style functionality
> feat(fetcher): add URL template path style support

- packages/wow/src/query/projection.ts
- packages/wow/test/query/projection.test.ts
- Update projection function to use a single options object instead of multiple parameters
- Add default parameter values to simplify function calls
- Enhance JSDoc comments for better code clarity and documentation
- Update unit tests to match the new function signature
> refactor(query): improve projection function signature and documentation

- packages/fetcher/src/fetchRequest.ts
- packages/fetcher/src/timeout.ts
- Add abortController property to FetchRequest interface
- Modify timeout handling to use custom AbortController if provided
- Update documentation to include new abortController property and its usage
> feat(fetcher): add support for custom AbortController in FetchRequest

- packages/wow/src/query/condition.ts
- Replace if statement with ternary operator for concise code
- Improve type checking for Condition or null/undefined
> refactor(query): simplify isValidateCondition function

- packages/cosec/src/jwtToken.ts
- packages/cosec/test/jwtToken.test.ts
- Change isExpired() method to isExpired property using
> refactor(cosec): convert isExpired, isRefreshNeeded, and isRefreshable to getters

- packages/cosec/src/jwtToken.ts
- packages/cosec/src/jwts.ts
- packages/cosec/test/jwtToken.test.ts
- Introduce EarlyPeriodCapable interface to handle early expiration
- Update JwtToken and JwtCompositeToken to support early expiration period
- Modify isTokenExpired function to consider early expiration
- Add earlyPeriod parameter to JwtCompositeTokenSerializer
> feat(jwt): add early expiration period for JWT tokens

- packages/cosec/src/tokenRefresher.ts
- packages/cosec/test/tokenRefresher.test.ts
- Add CoSecTokenRefresher class to handle token refreshing
- Implement TokenRefresher interface with refresh method
- Use Fetcher to send POST request to configured endpoint
- Add unit tests for CoSecTokenRefresher
> feat(tokenRefresher): implement CoSecTokenRefresher for token refreshing

- packages/cosec/src/authorizationRequestInterceptor.ts
- Add class and method-level JSDoc comments to AuthorizationRequestInterceptor
- Explain the purpose and functionality of the interceptor
- Provide details on token management and request interception process
> feat(cosec): add documentation to AuthorizationRequestInterceptor

- packages/fetcher/src/timeout.ts
- Assign the created AbortController to the request if not already present
- This ensures consistent handling of request cancellation
> fix(fatcher): ensure proper assignment of AbortController to request

- packages/cosec/test/authorizationRequestInterceptor.test.ts
- packages/eventstream/test/readableStreamAsyncIterable.test.ts
- packages/fetcher/test/fetchExchange.test.ts
- packages/fetcher/test/interceptorManager.test.ts
- packages/fetcher/test/mergeRequest.test.ts
- packages/fetcher/test/namedFetcher.test.ts
- Update import paths to use ../src instead of specific files
- Refactor test cases across multiple files for better readability and maintainability
- Remove unnecessary comments and assertions
> test: update import paths and refine test cases

- integration-test/package.json
- package.json
- packages/cosec/package.json
- packages/decorator/package.json
- packages/eventstream/package.json
- packages/fetcher/package.json
- packages/openapi/package.json
- packages/react/package.json
- packages/storage/package.json
- packages/viewer/package.json
- packages/wow/package.json
- Update version number in package.json files for all packages
- This is a minor version update for the Fetcher library
> build: bump version to 1.9.2

- packages/wow/src/types/bi.ts
- Create new BI module in types
- Add MessageHeaderSqlType enum with MAP and STRING values
- Update types index to include new BI module
> feat(types): add MessageHeaderSqlType enum for BI

- packages/wow/src/command/types.ts
- Add CompensationTarget interface for compensation operations
- Introduce DeleteAggregate interface for deleting aggregates
- Implement RecoverAggregate interface for recovering aggregates
- Import necessary types for new interfaces
> refactor(command): add new command interfaces and compensation target type

- packages/decorator/src/parameterDecorator.ts
- Add support for plain objects (Record) in PATH, QUERY, and HEADER parameter types,  allowing key-value pairs to be expanded into multiple parameters
- Extend ATTRIBUTE parameter type to support primitive types, plain objects (Record), and Map objects, with automatic expansion or entry addition
- Update documentation and examples for all parameter decorators to reflect new object expansion capabilities
- Modify parameter function to accept ATTRIBUTE type and include updated type descriptions in JSDoc
> feat(decorator): enhance parameter decorators with object expansion support

- packages/wow/src/types/index.ts
- Added export statement for endpoints types in main type definitions
> feat(types): export endpoints types

- packages/generator/src/client/queryClientGenerator.ts
- packages/generator/src/model/modelGenerator.ts
- packages/generator/src/model/modelInfo.ts
- packages/generator/src/utils/sourceFiles.ts
- Change QueryClientFactory to be exported
- Remove unused imports and related logic in modelGenerator
- Move wow type mapping logic to modelInfo- Adjust import path logic in sourceFiles utility
> refactor(generator): adjust import logic and export settings

- packages/generator/package.json
- Moved ts-morph from devDependencies to dependencies
- Ensured ts-morph is properly cataloged for generator package
- Removed duplicate ts-morph entry from devDependencies
> chore(generator): move ts-morph dependency to correct location

- packages/generator/src/baseCodeGenerator.ts
- packages/generator/src/cli.ts
- packages/generator/src/client/clientGenerator.ts
- packages/generator/src/client/commandClientGenerator.ts
- packages/generator/src/client/queryClientGenerator.ts
- packages/generator/src/index.ts
- packages/generator/src/model/modelGenerator.ts
- packages/generator/src/types.ts
- packages/generator/src/utils/logger.ts
- packages/generator/test/utils/logger.test.ts
- Added Logger interface with info, success, error, and progress methods
- Integrated logger into BaseCodeGenerator and all generator classes
- Added console logger implementation for CLI usage
- Enhanced client and model generators with detailed progress logging
- Added success and error logging for generation completion and failures
- Improved log messages for better visibility of generation process
- Passed logger instance through generator context to all components
> feat(generator): add logging support for code generation process

- .github/workflows/integration-test.yml
- integration-test/package.json
- Inserted 'Generate Code' step between 'Build' and 'Test' steps
- Configured the new step to run 'pnpm generate' command
- Ensured code generation occurs before integration tests execute
> feat(ci): add code generation step to integration test workflow

- packages/generator/README.md
- packages/generator/src/index.ts
- packages/generator/test-output/tsconfig.json
- packages/generator/test/index.test.ts
- packages/generator/test/utils/logger.test.ts
- Implemented recursive index file generation for all output directories
- Added export statements for both TypeScript files and subdirectories
- Integrated fs module for directory scanning and subdirectory detection
- Created logic to handle existing index files and create new ones
- Added comprehensive test coverage for index generation functionality
- Updated README documentation with index generation features
- Enhanced logger tests with additional parameter validation cases
- Optimized source file formatting and import organization process
> feat(generator): add automatic index.ts file generation

- packages/generator/src/index.ts
- Added informational logs for key steps in the generation pipeline
- Implemented detailed logging for OpenAPI parsing and aggregate resolution
- Added progress tracking for model, client, and index file generation
- Included success confirmation messages for each major generation phase- Enhanced error logging for file system operations
- Added file optimization progress tracking with completion confirmation
> feat(generator): add comprehensive logging to code generation process

- packages/generator/README.zh-CN.md
- packages/generator/package.json
- Add README.zh-CN.md with comprehensive Chinese documentation
- Update package.json to include README.zh-CN.md in files
- Modify description in package.json to remove extra space
- Update README.md to link to Wow framework repository
> docs(generator): add Chinese documentation and update package files

- packages/generator/src/client/commandClientGenerator.ts
- Imported isEmptyObject utility function
- Added conditional check for empty object schema in command request parameter
- Improved type safety for command client generation
> feat(generator): add isEmptyObject check for command request parameter

- packages/generator/src/model/modelGenerator.ts
- packages/generator/test/model/modelGenerator.test.ts
- Add OptionalKind and PropertySignatureStructure imports
- Implement hasQuestionToken for optional properties
- Update test cases to verify optional property handling
> feat(generator): support optional properties in model generation

- packages/generator/src/utils/naming.ts
- Extracted common name splitting logic into reusable splitName function
- Added comprehensive JSDoc documentation for splitName function
- Refactored pascalCase function to use new splitName utility
- Implemented new upperSnakeCase function for UPPER_SNAKE_CASE conversion
- Added proper JSDoc documentation for upperSnakeCase function
- Exported upperSnakeCase function for external use
> feat(generator): add splitName utility and upperSnakeCase converter

- .github/workflows/release.yml
- scripts/publish-npm.sh
- Extracted npm publish workflow into separate shell script
- Updated GitHub Actions workflow to call publish script
- Added error handling and logging to publish script
> chore(release): move npm publish logic to dedicated script

- packages/fetcher/src/fetchRequest.ts
- Introduced RequestBodyType type alias for flexible body types
- Added generic type parameter to FetchRequestInit interface
- Updated FetchRequest interface to extend generic FetchRequestInit
- Enhanced type safety for request body handling
- Maintained backward compatibility with existing code
- Improved documentation for request configuration interfaces
> feat(fetcher): add generic type support for request body

- packages/decorator/src/parameterDecorator.ts
- packages/wow/src/command/commandRequest.ts
- Import RequestBodyType from @ahoo-wang/fetcher
- Update ParameterRequest interface to accept generic body type
- Extend FetchRequestInit with generic body type parameter
- Modify CommandRequest to pass generic body type to ParameterRequest
> feat(decorator): enhance ParameterRequest with generic body type support

- packages/generator/src/model/modelGenerator.ts
- packages/generator/test/e2e.test.ts
- Added support for detecting wow aggregated schemas with various suffixes
- Implemented state aggregate checking based on model info and context aggregates
- Improved test output directory cleanup to remove only subdirectories
- Added error handling for test directory removal operations
- Updated e2e tests to use new directory cleanup function
> feat(generator): enhance schema aggregation detection and improve test cleanup

- packages/generator/src/utils/naming.ts
- Eliminated unnecessary conditional check for empty parts
- Simplified map function logic by removing redundant condition
- Improved code clarity in name transformation pipeline
> fix(generator): remove redundant empty string check in naming utility

- packages/fetcher/src/resultExtractor.ts
- packages/fetcher/test/resultExtractor.test.ts
- packages/generator/test/model/modelInfo.test.ts
- Added BlobResultExtractor to handle response body as Blob
- Added ArrayBufferResultExtractor to handle response body as ArrayBuffer
- Added BytesResultExtractor to handle response body as Uint8Array
- Updated ResultExtractors object to include new extractors
- Added unit tests for new result extractors
> feat(fetcher): add Blob, ArrayBuffer, and Bytes result extractors

- packages/react/src/fetcher/useFetcher.ts
- Imported useRequestId hook from core module
- Generated unique request id for each fetch operation
- Added request id validation to prevent race conditions
- Updated effect dependencies to include requestId
- Ensured state updates only occur for latest request
- Maintained backward compatibility with existing options
> feat(react): add request id tracking to useFetcher hook

- packages/react/src/core/useExecutePromise.ts
- Add generic type parameter E for error handling
- Update usePromiseState to accept error type parameter
- Cast caught errors to specified error type E
> feat(react): enhance useExecutePromise with generic error type

- packages/fetcher/src/timeout.ts
- Added await keyword to fetch calls to ensure proper async handling
- Fixed potential race conditions in request processing
- Improved abort signal delegation logic
- Enhanced timeout management for fetch requests
- Resolved issues with asynchronous request initialization
- Updated abort controller integration for better cancellation support
> fix(fetcher): await fetch calls to handle async properly

- packages/react/src/wow/useListQuery.ts
- packages/react/src/wow/useListQueryState.ts
- packages/react/src/wow/useListStreamQuery.ts
- Extracted query state logic (condition, projection, sort, limit) into a new reusable hook
- Removed duplicate state management code from useListQuery and useListStreamQuery
- Simplified component logic by delegating state updates to the new hook
- Improved code maintainability and reduced redundancy across query hooks
- Added centralized query building functionality in the new hook
- Updated dependencies and imports to reflect the refactored structure
> refactor(wow): extract list query state management to useListQueryState

- packages/react/test/core/useExecutePromise.test.ts
- packages/react/test/wow/useCountQuery.test.ts
- packages/react/test/wow/useListQuery.test.ts
- packages/react/test/wow/useListStreamQuery.test.ts
- packages/react/test/wow/usePagedQuery.test.ts
- packages/react/test/wow/useSingleQuery.test.ts
- Added test cases for autoExecute true/false/not provided
> test(wow): add autoExecute mount behavior tests

- packages/eventstream/src/responses.ts
- Add contentType property with configurable descriptor
- Add isEventStream property with configurable descriptor
- Add eventStream method with configurable descriptor
- Prevent overriding existing properties on Response prototype
- Improve property definition safety and flexibility
> feat(eventstream): add configurable property definitions for Response prototype
