Ahoo-Wang/fetcher

packages/decorator/README.md, packages/decorator/README.zh-CN.md, packages/decorator/src/requestExecutor.ts, packages/decorator/test/apiDecorator.test.ts
- Include the method property in the object returned by the execute function
- This ensures that the HTTP method (GET, POST, etc.) is properly set when making requests
=> fix(decorator): add method property to RequestExecutor execute function

examples/package.json, examples/src/basic-usage.ts, package.json, packages/cosec/package.json, packages/decorator/package.json, packages/eventstream/package.json, packages/fetcher/package.json, packages/fetcher/src/types.ts, packages/fetcher/test/fetcher.test.ts
- Extend the Response interface with a generic json() method
- Update basic-usage.ts to demonstrate type-safe response handling
- Add unit test to verify generic type support for response json()
=> feat(types): add type-safe json() method to Response interface

packages/decorator/README.md, packages/decorator/README.zh-CN.md, packages/decorator/src/parameterDecorator.ts, packages/decorator/src/requestExecutor.ts, packages/decorator/test/apiDecorator.test.ts, packages/decorator/test/parameterDecorator.test.ts, packages/decorator/test/requestExecutor.resolveRequest.test.ts, packages/decorator/test/requestExecutor.test.ts, packages/fetcher/src/index.ts, packages/fetcher/src/mergeRequest.ts, packages/fetcher/test/mergeRequest.test.ts
- Add @request() decorator to pass a complete FetcherRequest object
- Implement advanced request merging strategy:
- Recursive merge of nested objects (path, query, headers)
- Override of primitive values (method, body, timeout, signal)
- Graceful handling of empty objects
- Update documentation and add new test cases
=> feat(decorator): add @request() decorator and enhance request merging 

packages/decorator/test/reflection.branch.test.ts
- Add test cases for arrow function with unmatched parentheses and regular function with no opening parenthesis
- Ensure that the `getParameterNames` function can handle these edge cases without throwing errors
=> test(decorator): add robustness tests for function parameter parsing

packages/cosec/src/cosecRequestInterceptor.ts, packages/cosec/src/cosecResponseInterceptor.ts, packages/decorator/package.json, packages/eventstream/package.json, packages/eventstream/src/eventStreamInterceptor.ts, packages/fetcher/README.md, packages/fetcher/README.zh-CN.md, packages/fetcher/src/fetchInterceptor.ts, packages/fetcher/src/requestBodyInterceptor.ts, packages/fetcher/src/urlResolveInterceptor.ts, packages/fetcher/test/fetcherInterceptors.test.ts, packages/fetcher/test/requestBodyInterceptor.test.ts, packages/fetcher/test/urlResolveInterceptor.test.ts
- Update interceptor orders to allow more flexibility for custom interceptors
- CoSecRequestInterceptor: Number.MIN_SAFE_INTEGER + 1000
- CoSecResponseInterceptor: Number.MAX_SAFE_INTEGER -100
- EventStreamInterceptor: Number.MAX_SAFE_INTEGER - 100
- FetchInterceptor: Number.MAX_SAFE_INTEGER - 100
- RequestBodyInterceptor: Number.MIN_SAFE_INTEGER + 200
- UrlResolveInterceptor: Number.MIN_SAFE_INTEGER + 100
=> refactor(fetcher): adjust interceptor orders for better extensibility

packages/cosec/src/cosecRequestInterceptor.ts, packages/decorator/src/requestExecutor.ts, packages/fetcher/src/fetchExchange.ts, packages/fetcher/src/fetchRequest.ts, packages/fetcher/src/fetcher.ts, packages/fetcher/src/index.ts, packages/fetcher/src/mergeRequest.ts
- Rename FetcherRequest to FetchRequestInit in multiple files
- Update related imports and usages accordingly
- Move FetchRequestInit definition to a separate file
=> refactor(fetched): rename FetcherRequest to FetchRequestInit

packages/decorator/src/apiDecorator.ts
- Replace HeadersCapable with RequestHeadersCapable in ApiMetadata interface
- Update headers property type from Record<string, string> to RequestHeaders
=> refactor(decorator): update API metadata to use RequestHeaders type

packages/wow/src/query/condition.ts
- Create dedicated ConditionOptions interface for condition options
- Update related functions to use ConditionOptions instead of Record<string, any>
- Reorganize interface and enum declarations for better structure and readability
=> refactor(query): improve ConditionOptions typing and interface reorganization

README.md, README.zh-CN.md, examples/src/interceptorExample.ts, packages/cosec/src/cosecRequestInterceptor.ts, packages/cosec/src/cosecResponseInterceptor.ts, packages/cosec/test/cosecRequestInterceptor.test.ts, packages/cosec/test/cosecResponseInterceptor.test.ts, packages/decorator/src/requestExecutor.ts, packages/eventstream/src/eventStreamInterceptor.ts, packages/eventstream/test/eventStreamInterceptor.comprehensive.test.ts, packages/eventstream/test/eventStreamInterceptor.integration.test.ts, packages/eventstream/test/eventStreamInterceptor.test.ts, packages/fetcher/README.md, packages/fetcher/README.zh-CN.md, packages/fetcher/src/fetchExchange.ts, packages/fetcher/src/fetchInterceptor.ts, packages/fetcher/src/fetcher.ts, packages/fetcher/src/interceptor.ts, packages/fetcher/src/requestBodyInterceptor.ts, packages/fetcher/src/timeout.ts, packages/fetcher/src/urlResolveInterceptor.ts, packages/fetcher/test/fetcher-exchange.test.ts, packages/fetcher/test/fetcher-interceptor.test.ts, packages/fetcher/test/interceptor.test.ts, packages/fetcher/test/requestBodyInterceptor.test.ts, packages/fetcher/test/urlResolveInterceptor.test.ts
- Update interceptor functions to return void instead of FetchExchange
- Modify Fetcher.exchange method to not expect a return value from interceptors
- Remove unnecessary return statements and type annotations in interceptors
=> refactor(fetcher): change interceptor return type to void

packages/fetcher/README.md, packages/fetcher/README.zh-CN.md, packages/fetcher/src/fetcher.ts, packages/fetcher/src/index.ts, packages/fetcher/src/interceptorManager.ts, packages/fetcher/test/fetcher-exchange.test.ts, packages/fetcher/test/fetcherInterceptors.test.ts, packages/fetcher/test/interceptor.test.ts, packages/fetcher/test/interceptorManager.test.ts
- Rename FetcherInterceptors class to InterceptorManager
- Update related imports and references across the codebase
- Modify test files to use the new InterceptorManager name
- Update README files to reflect the new class name
=> refactor(fetcher): rename FetcherInterceptors to InterceptorManager

packages/fetcher/src/fetcherError.ts, packages/fetcher/src/index.ts, packages/fetcher/src/interceptorManager.ts
- Relocate ExchangeError class from fetcherError.ts to interceptorManager.ts
- Remove ExchangeError import from fetcherError.ts
- Add FetcherError import to interceptorManager.ts
- Update class definition and examples in interceptorManager.ts
=> refactor(fetcher): move ExchangeError to interceptorManager

packages/eventstream/src/serverSentEventTransformStream.ts
- Add DEFAULT_EVENT_TYPE constant to avoid magic string
- Replace hardcoded 'message' with DEFAULT_EVENT_TYPE in event assignment
- Update comments to reflect the use of the new constant
=> refactor(eventstream): introduce DEFAULT_EVENT_TYPE constant for 'message'

packages/fetcher/src/fetchExchange.ts, packages/fetcher/src/fetcher.ts, packages/fetcher/src/fetcherError.ts, packages/fetcher/src/interceptorManager.ts, packages/fetcher/test/fetchExchange.test.ts, packages/fetcher/test/fetcherError.test.ts
- Remove FetchError class and its related imports
- Add requiredResponse getter to FetchExchange, throwing ExchangeError when no response
- Update Fetcher to use requiredResponse, ensuring a response is always returned
- Modify ExchangeError to accept an optional error message
- Remove FetchError related tests
=> refactor(fetcher): remove FetchError and simplify error handling 

packages/decorator/src/resultExtractor.ts, packages/decorator/test/requestExecutor.branch.test.ts, packages/decorator/test/requestExecutor.execute.test.ts
- Set ResultExtractors.DEFAULT to JsonResultExtractor instead of ResponseResultExtractor
- Update tests to reflect the new default result extractor behavior
- Modify expectations in tests to match the output of JsonResultExtractor
=> refactor(decorator): change default result extractor to Json

packages/eventstream/src/index.ts, packages/eventstream/src/jsonServerSentEventTransformStream.ts, packages/eventstream/test/jsonServerSentEventTransformStream.test.ts
- Implement JsonServerSentEventTransformStream to convert ServerSentEvent to JsonServerSentEvent
- Add toJsonServerSentEventStream function to easily convert ServerSentEventStream to JsonServerSentEventStream
- Include unit tests for JsonServerSentEventTransformStream and toJsonServerSentEventStream
=> feat(eventstream): add support for JSON Server-Sent Events

packages/cosec/vite.config.ts, packages/decorator/vite.config.ts, packages/eventstream/vite.config.ts, packages/fetcher/vite.config.ts, packages/wow/vite.config.ts
- Add sourcemap: true to vite.config.ts for cosec, decorator, eventstream, fetcher, and wow packages
- This change improves debugging by providing source maps for all components
=> build: enable source map generation for all packages

packages/cosec/vite.config.ts
- Include 'nanoid' in the external dependencies for the Vite build configuration
- Add a global reference for 'nanoid' to ensure proper module resolution
=> build(cosec): add nanoid as an external dependency

packages/decorator/vite.config.ts
- Add 'reflect-metadata' to external dependencies in vite.config.ts
- This change prevents bundling reflect-metadata with the decorator package
=> build(decorator): add reflect-metadata as external dependency

packages/fetcher/src/fetchRequest.ts, packages/fetcher/src/types.ts
- Use ContentTypeHeader constant instead of hardcoded 'Content-Type' in RequestHeaders interface
- Add PartialBy utility type to create new types with optional properties
- Update NamedCapable interface documentation
=> feat(fetcher): Add PartialBy utility type to create new types with optional properties

packages/wow/src/query/event/eventStreamQueryApi.ts, packages/wow/src/query/snapshot/snapshotQueryApi.ts
- Add eslint-disable comment for no-empty-object-type rule in EventStreamQueryApi and SnapshotApi interfaces
- This change allows the interfaces to extend QueryServiceApi without including the 'single' method
=> refactor(query): disable ESLint empty object type rule for specific interfaces

packages/wow/src/query/index.ts, packages/wow/src/query/pagination.ts, packages/wow/src/query/projection.ts, packages/wow/src/query/queryable.ts, packages/wow/src/query/sort.ts, packages/wow/test/command/commandResult.test.ts, packages/wow/test/query/pagination.test.ts, packages/wow/test/query/projection.test.ts, packages/wow/test/query/sort.test.ts
- Move Pagination, Projection, and Sort interfaces to their own files
- Create new functions for creating pagination and projection objects
- Add unit tests for pagination, projection, and sort functionalities
- Update imports in queryable.ts to use new separate files
=> refactor(query): split query related interfaces and functions into separate files

packages/cosec/src/types.ts, packages/eventstream/src/eventStreamInterceptor.ts, packages/eventstream/src/serverSentEventTransformStream.ts, packages/eventstream/test/serverSentEventTransformStream.test.ts, packages/fetcher/src/fetchRequest.ts
- Replace CoSecHeaders enum with static readonly class
- Replace ResponseCodes enum with static readonly class
- Replace ServerSentEventField enum with static readonly class
- Update related imports and usages across multiple files
=> refactor(types): replace enums with static readonly classes

packages/wow/src/query/condition.ts, packages/wow/src/query/snapshot/snapshot.ts, packages/wow/test/query/snapshot/snapshot.test.ts
- Add SnapshotMetadataFields class to provide field names for snapshot metadata
- Update snapshot interfaces to use the new metadata fields
- Modify condition.ts to use static readonly properties instead of enum
- Refactor snapshot test file structure for better organization
=> feat(query): add snapshot metadata fields and update related tests

packages/eventstream/src/eventStreamInterceptor.ts, packages/eventstream/src/types.ts, packages/eventstream/test/eventStreamInterceptor.test.ts
- Add new methods to throw an error if event stream is not supported
- Update response handling for non-event stream content types
- Extend EventStreamResponse interface with new required methods
=> feat(eventstream): add requiredEventStream and requiredJsonEventStream methods

packages/decorator/src/resultExtractor.ts, packages/decorator/test/resultExtractor.test.ts
- Replace exchange.requiredResponse.eventStream with requiredEventStream
- Replace exchange.requiredResponse.jsonEventStream with requiredJsonEventStream
- Update unit tests to use new requiredEventStream and requiredJsonEventStream methods
- Remove unnecessary ExchangeError import and usage
=> refactor(decorator): use requiredEventStream and requiredJsonEventStream

integration-test/test/wow/eventStreamQueryClient.test.ts, integration-test/test/wow/snapshotQueryClient.test.ts, packages/wow/src/query/event/domainEventStream.ts, packages/wow/src/query/event/eventStreamQueryClient.ts, packages/wow/src/query/event/index.ts, packages/wow/src/query/queryApi.ts, packages/wow/src/query/snapshot/snapshotQueryClient.ts, packages/wow/src/types/client.ts, packages/wow/test/query/event/domainEventStream.test.ts, packages/wow/vitest.config.ts
- Add EventStreamQueryClient for querying event streams
- Refactor SnapshotQueryClient to use new QueryClient base class
- Update integration tests for new and modified query clients
- Rename DomainEventStreamHeaders to DomainEventStreamHeader
- Move common query logic to QueryClient class
=> feat(wow): implement EventStreamQueryClient and refactor query clients

packages/fetcher/src/urlBuilder.ts, packages/fetcher/src/urls.ts, packages/fetcher/test/urlBuilder.test.ts, packages/fetcher/test/urls.test.ts
- Move interpolateUrl function from UrlBuilder to urls.ts
- Add extractPathParams function to urls.ts
- Update related tests to use new functions
- Remove interpolateUrl from UrlBuilder class
=> refactor(fetcher): move interpolateUrl to urls.ts and add extractPathParams

integration-test/test/wow/commandClient.test.ts, packages/wow/src/command/commandRequest.ts
- Introduce AddCartItem interface for cart item addition
- Update CommandRequest to use a generic type for body
- Enhance type safety and reduce potential for runtime errors
=> refactor(wow): add type safety to CommandRequest

packages/wow/src/command/commandClient.ts, packages/wow/src/query/event/eventStreamQueryClient.ts, packages/wow/src/query/queryApi.ts, packages/wow/src/query/snapshot/snapshotQueryApi.ts, packages/wow/src/query/snapshot/snapshotQueryClient.ts
- Add type parameter T to methods in QueryApi, SnapshotQueryApi, EventStreamQueryClient, and CommandClient
- Remove redundant type definitions and improve type inference
- Update method signatures to use the new type parameter for partial resource types
=> refactor(wow): add type parameter for partial resource type

packages/fetcher/src/fetcher.ts, packages/fetcher/src/urlBuilder.ts
- Introduce `urlTemplateStyle` option in `FetcherOptions`
- Update `UrlBuilder` to support different URL template styles
- Add `UrlTemplateStyle` enum and `getUrlTemplateResolver` function
- Enable customization of path parameter parsing and resolution
=> feat(fetcher): add URL template style configuration

packages/cosec/vite.config.ts, packages/decorator/vite.config.ts, packages/eventstream/vite.config.ts, packages/fetcher/vite.config.ts, packages/wow/vite.config.ts
- Removed `vite-bundle-analyzer` import and configuration from multiple packages
- This change affects `cosec`, `decorator`, `eventstream`, `fetcher`, and `wow` packages
=> build(vite): remove bundle analyzer from vite configurations

packages/fetcher/src/fetchExchange.ts, packages/fetcher/test/fetchExchange.test.ts
- Implement ensureRequestHeaders method to guarantee request headers object exists
- Update tests to cover new functionality
- Add type import for RequestHeaders
=> feat(fetcher): add ensureRequestHeaders method to FetchExchange

packages/wow/src/query/queryable.ts, packages/wow/test/query/queryable.test.ts
- Implement listQuery factory function for creating ListQuery objects
- Add default pagination size constant
- Update import statements to include new and existing components
- Add comprehensive unit tests for listQuery functionality
=> feat(query): add listQuery factory function and update related tests

packages/fetcher/src/timeout.ts, packages/fetcher/test/timeout.test.ts
- Refactor timeoutFetch to handle optional timeout and existing AbortSignal
- Add support for delegating to native fetch when request.signal is present
- Update function documentation to reflect new behavior
- Add unit test for request.signal delegation
=> feat(fetcher): improve timeout handling and support existing signals

packages/fetcher/src/fetcher.ts, packages/fetcher/src/index.ts, packages/fetcher/src/resultExtractor.ts, packages/fetcher/test/fetcher.test.ts, packages/fetcher/test/resultExtractor.test.ts
- Add ResultExtractor interface for transforming FetchExchange into specific result types
- Implement common result extractors in ResultExtractors namespace:
- Exchange: returns the original FetchExchange object
- Response: extracts the Response object from the exchange
- Json: parses the response body as JSON
- Text: extracts the response body as text
- Create unit tests for ResultExtractor and ResultExtractors to ensure proper functionality
=> feat(fetcher): implement ResultExtractor and related tests

packages/wow/package.json, packages/wow/src/command/commandClient.ts, packages/wow/src/query/event/eventStreamQueryClient.ts, packages/wow/src/query/queryApi.ts, packages/wow/src/query/snapshot/snapshotQueryClient.ts, pnpm-lock.yaml
- Update command and query clients to use JsonEventStreamResultExtractor instead of ResultExtractors.JsonEventStream
- Remove unused import of ResultExtractors from fetcher-decorator
- Update package.json to remove dependency on fetcher-decorator
=> refactor(wow): replace ResultExtractors with JsonEventStreamResultExtractor

packages/fetcher/src/mergeRequest.ts
- Add abortController to the list of properties merged from second to first request
- Ensure second.request's abortController takes precedence if present
=> fix(fetcher): merge abortController in request merge

packages/wow/src/query/condition.ts, packages/wow/test/query/condition.test.ts
There is OR condition creators in packages/wow/src/query/condition.ts
They did not filter empty conditions, we should ensure each of condition from arguments is a validate condition
=> feat(wow): allow empty condition in OR condition Creators

packages/cosec/src/cosecResponseInterceptor.ts, packages/cosec/test/cosecResponseInterceptor.test.ts
- Replace `exchange.fetcher.request` with `exchange.fetcher.interceptors.exchange` for retrying requests
- This change ensures that all interceptors are properly executed during the retry process
=> fix(cosec): use interceptor exchange method for retrying requests

packages/cosec/src/storage/browserListenableStorage.ts, packages/cosec/src/storage/inMemoryListenableStorage.ts, packages/cosec/src/storage/listenableStorage.ts
- Update StorageListener type to expect StorageEventInit instead of StorageEvent
- Modify listener calls in browserListenableStorage and inMemoryListenableStorage
- Remove unnecessary StorageEvent import in inMemoryListenableStorage
=> refactor(storage): change StorageListener type to use StorageEventInit

packages/cosec/src/deviceIdStorage.ts, packages/cosec/test/deviceIdStorage.test.ts
- DeviceIdStorage now extends KeyStorage<string>
- Uses IdentitySerializer for string serialization
- Storage key is now configurable upon instantiation
- Removed unnecessary methods and simplified existing ones
- Updated tests to reflect new implementation
=> refactor(deviceIdStorage): inherit from KeyStorage and use IdentitySerializer

packages/fetcher/src/fetcher.ts
- Add resultExtractor parameter to fetch() method
- Update methodFetch() to accept resultExtractor
- Modify HTTP method functions (get, post, etc.) to support resultExtractor
- Update types and add generics for better type checking
=> feat(fetcher): add result extractor support for HTTP methods

packages/react/src/storage/useKeyStorage.ts
- Rename 'store' to 'value' to better reflect the data it holds
- This change enhances code readability and maintainability
=> refactor(react): improve variable naming in useKeyStorage

packages/cosec/README.md, packages/cosec/README.zh-CN.md
- Update README.md and README.zh-CN.md with new CoSec integration information
- Rename CoSecRequestInterceptor to AuthorizationRequestInterceptor
- Rename CoSecResponseInterceptor to AuthorizationResponseInterceptor
- Remove integration test example from README
- Add information about pluggable architecture
=> docs(cosec): update README and rename interceptors

integration-test/package.json, package.json, packages/cosec/package.json, packages/decorator/package.json, packages/eventstream/package.json, packages/fetcher/package.json, packages/react/package.json, packages/storage/package.json, packages/wow/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
- Replace individual package dependencies with centralized workspace catalog
- Update dependency specifiers to use 'catalog:' instead of specific versions
- Remove redundant dependencies from package.json files
- Update pnpm-lock.yaml to reflect new dependency structure
=> build(deps): switch to pnpm workspace catalog

packages/fetcher/src/fetcher.ts, packages/fetcher/src/requestBodyInterceptor.ts, packages/fetcher/test/requestBodyInterceptor.test.ts
- Remove 'Content-Type' from DEFAULT_HEADERS constant
- This change simplifies the default request headers configuration
=> refactor(fetcher): remove unnecessary default content type header

pnpm-lock.yaml, pnpm-workspace.yaml
- Update pnpm-workspace.yaml to use consistent double quotes for version numbers
- Alphabetically sort the dependencies in the catalog section
- Adjust indentation for better readability
=> build(deps): update pnpm workspace dependencies

packages/viewer/test/index.test.ts
- Add a new test file index.test.ts in the viewer package
- Implement a test to ensure that all exports are properly defined in index.ts
- Use dynamic import to check module exports without causing circular dependencies
=> test(viewer): add test case for index.ts module exports

packages/wow/src/command/types.ts
- Define BatchResult interface to represent the result of a batch operation
- Include pagination and error information in the BatchResult
- Extend ErrorInfo to include error details if the batch operation failed
- Add 'after' field for the next item cursor/identifier for pagination
- Add 'size' field for the number of items in the current batch
=> feat(command): add BatchResult interface for batch operation results

packages/wow/src/command/commandResult.ts, packages/wow/src/command/types.ts, packages/wow/src/types/modeling.ts
- Add WaitSignal interface to represent a signal waiting for command execution completion
- Enhance NullableAggregateVersionCapable interface with detailed comments
- Introduce AggregateIdCapable interface in modeling.ts
- Update import in commandResult.ts to include AggregateIdCapable
=> refactor(command): add WaitSignal interface and improve type definitions

packages/decorator/src/functionMetadata.ts, packages/decorator/src/parameterDecorator.ts, packages/decorator/test/functionMetadata.test.ts, packages/decorator/test/parameterDecorator.test.ts
The `@attributes` parameter decorator has been removed in favor of usingthe `@attribute` decorator with an object value. This change simplifiesthe API and reduces redundancy in handling request attributes.
The `ParameterType.ATTRIBUTES` enum member and its associated processing logic have also been removed from the metadata handling code.
=> feat(decorator): remove deprecated `@attributes` parameter decorator

packages/wow/src/command/commandRequest.ts, packages/wow/src/types/endpoints.ts
- Renamed PathParams interface to UrlPathParams for clarity
- Updated import statements to use UrlPathParams
- Changed CommandUrlParams path property type to UrlPathParams
- Improved type consistency across command request interfaces
=> refactor(types): rename PathParams to UrlPathParams

packages/wow/src/command/commandRequest.ts
- Updated CommandRequest interface to allow optional body property
- Changed body type from required C to optional C | undefined
- This change enables commands that don't require a body payload
=> fix(command): make command request body optional

packages/wow/src/command/commandRequest.ts
- Removed RequiredBy<ParameterRequest, 'path'> constraint
- Made path parameter optional in CommandRequest interface
- Updated interface to extend ParameterRequest directly
- Maintained backward compatibility with existing implementations
=> refactor(command): remove RequiredBy constraint from CommandRequest

packages/wow/src/query/queryClients.ts, packages/wow/test/query/queryClients.test.ts
- Replace standalone functions with QueryClientFactory class
- Add support for default options in factory constructor
- Merge default and instance options when creating clients
- Maintain existing snapshot query client functionality
- Maintain existing event stream query client functionality
- Update JSDoc comments to reflect new factory pattern
=> refactor(query): introduce QueryClientFactory for creating query clients

packages/generator/expected/compensation/execution_failed/queryClient.ts, packages/wow/src/types/endpoints.ts, packages/wow/test/types/endpoints.test.ts
- Updated enum value from DEFAULT to NONE in endpoints.ts- Changed corresponding test expectation in endpoints.test.ts- Updated query client configuration to use NONE instead of DEFAULT
=> refactor(endpoints): rename DEFAULT to NONE in ResourceAttributionPathSpec

packages/wow/src/types/endpoints.ts, packages/wow/test/types/endpoints.test.ts
- Added leading slash to TENANT path specification
- Added leading slash to OWNER path specification
- Added leading slash to TENANT_OWNER path specification
- Updated test cases to match new path formats
- Adjusted example comments to reflect correct path usage
=> fix(wow): update ResourceAttributionPathSpec paths to include leading slash

packages/generator/src/cli.ts, packages/generator/src/client/clientGenerator.ts, packages/generator/src/client/commandClientGenerator.ts, packages/generator/src/client/queryClientGenerator.ts, packages/generator/src/utils/openAPIParser.ts, packages/generator/src/utils/operations.ts
- Rename imported BaseCodeGenerator path from uppercase to lowercase
- Remove unused underscore variables in for-of loops
- Add JSDoc comments to CommandClientGenerator and QueryClientGenerator classes
- Add JSDoc comments to CLI entry point and update program description
- Simplify array declarations and import statements
- Update extractOkResponse function with JSDoc documentation
- Fix JSON parsing catch block to remove unused error parameter
- Adjust function parameter formatting for better readability
=> refactor(generator): improve code generation and CLI entry point

packages/generator/src/utils/sourceFiles.ts, packages/generator/test/utils/sourceFiles.test.ts
- Add conditional path handling for import aliases in addImportRefModel
- - Improve jsDoc utility to properly filter and join title/description
- Implement comprehensive test coverage for import and JSDoc functions
- Add support for JSDoc comment generation with proper filtering
- Extend import logic to prevent duplicate imports for same paths
- Introduce addJSDoc helper for adding documentation comments to nodes
=> feat(generator): enhance import handling and JSDoc utilities

packages/cosec/package.json, pnpm-workspace.yaml
- Replace direct nanoid version with catalog reference in package.json
- Add nanoid to pnpm workspace catalog with version ^5.1.6
- Ensure consistent dependency management across workspace packages
=> chore(deps): update nanoid dependency to catalog version

packages/generator/src/model/modelGenerator.ts, packages/generator/src/utils/schemas.ts, packages/generator/test/utils/sourceFiles.test.ts
- Add beforeEach hook to clear mock states
- Replace external mock import with inline mock objects
- Update assertions to match new mock structure
- Remove unused mocked function references
- Adjust module specifier paths in assertions
- Ensure proper mocking of ts-morph methods
=> test(sourceFiles): refactor tests to use inline mocks

packages/generator/src/utils/sourceFiles.ts, packages/generator/test/utils/sourceFiles.test.ts
- Simplify import path logic by removing conditional checks
- Always combine output directory with model file name
- Ensure module specifier starts with import alias
- Update test case to match new path handling behavior
=> fix(generator): resolve import path handling for ref models

packages/generator/src/utils/sourceFiles.ts, packages/generator/test/utils/sourceFiles.test.ts
- Replace combineURLs with path.join and path.relative for accurate relative paths
- Remove unused IMPORT_WOW_PATH constant
- Add .ts extension removal in module specifier
- Ensure relative paths start with ./ when necessary
- Update tests to reflect new relative path generation
- Mock getDirectoryPath in test utilities for proper path resolution testing
=> refactor(generator): update import path resolution logic

packages/generator/src/cli.ts, packages/generator/test/cli.test.ts
- Imported package.json directly in CLI setup
- Replaced hardcoded version string with dynamic import
- Updated tests to mock fs and path modules properly
- Adjusted test assertions to check against packageJson.version
- Ensured proper mocking order for fs and path in tests
- Added implementation details for join mock in tests
=> feat(generator): dynamically load CLI version from package.json

packages/generator/package.json
- Updated test script timeout from 10000ms to 15000ms
- Ensures sufficient time for test completion in CI environments
- Prevents premature test termination due to timeout limits
- Maintains existing coverage and run configurations
- Aligns timeout setting with typical test execution requirements
=> chore(test): increase test timeout to 15000ms

packages/generator/src/model/modelInfo.ts, packages/generator/test/e2e.test.ts, packages/generator/test/model/modelInfo.test.ts, packages/generator/test/utils/operations.test.ts, packages/generator/test/utils/schemas.test.ts
- Removed fallback logic for cases where no part starts with uppercase
- Simplified path construction by removing unnecessary conditional check
- Preserved core functionality for extracting model name and path segments
=> refactor(model): remove redundant model name handling logic

packages/generator/src/client/apiClientGenerator.ts, packages/generator/src/client/commandClientGenerator.ts, packages/generator/src/client/decorators.ts
- Added `addImportEventStream` utility to handle event stream imports
- Updated `apiClientGenerator` to use the new event stream import helper
- Modified `commandClientGenerator` to utilize event stream import utility
- Removed direct import declaration for `JsonEventStreamResultExtractor`
- Introduced `EVENTSTREAM_MODULE_SPECIFIER` constant for better maintainability
- Enhanced decorator utilities to support event stream result extraction
=> feat(generator): add event stream support in client generators

packages/react/src/fetcher/useFetcher.ts, packages/react/test/fetcher/useFetcher.test.ts
- Replace import of default fetcher with fetcher registrar
- Update useFetcher hook to use fetcher from registrar
- Update mock implementation in tests to use fetcher registrar
=> refactor(fetcher): replace default fetcher with fetcher registrar

packages/react/src/core/usePromiseState.ts
- Add useRef to track latest options object
- Update onSuccess callback to use ref value
- Update onError callback to use ref value
- Remove options from useCallback dependencies
- Ensure callbacks always use current options
=> fix(usePromiseState): prevent stale options reference in callbacks

packages/react/src/core/usePromiseState.ts, packages/react/src/core/useRequestId.ts, packages/react/src/fetcher/useFetcher.ts
- Import useMemo from react
- Wrap hook return value with useMemo to prevent unnecessary re-renders
- Add dependency array to useMemo for proper memoization
- Maintain existing hook functionality while improving performance
=> refactor(react): optimize useRequestId hook with useMemo

packages/react/README.md, packages/react/README.zh-CN.md, packages/react/src/core/useExecutePromise.ts, packages/react/src/core/usePromiseState.ts, packages/react/src/fetcher/useFetcher.ts, packages/react/test/core/useExecutePromise.test.ts, packages/react/test/core/usePromiseState.test.ts, packages/react/test/fetcher/useFetcher.test.ts
- Add async support for onSuccess and onError callbacks
- Update setSuccess and setError to return promises
- Handle async callback errors with try/catch blocks
- Update documentation with async callback examples
- Fix test cases to await async state updates
- Improve type definitions for callback signatures
- Update README with async callback usage examples
=> feat(react): support async callbacks in promise state hooks

pnpm-lock.yaml
- Updated typescript dependency from 5.9.2 to 5.9.3
- Updated related dependencies including typescript-eslint and unplugin-dts
- Updated msw and vitest packages to use the new typescript version
- Removed old typescript5.9.2 entries from lockfile
- Updated all package references to use typescript5.9.3
=> chore(deps): update typescript to v5.9.3

packages/generator/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
- Removed @types/yaml from generator package devDependencies
- Removed @types/yaml from pnpm workspace catalog
- Clean up unused type definitions to reduce dependency footprint
=> chore(deps): remove unused @types/yaml dependency

pnpm-lock.yaml, pnpm-workspace.yaml
- Updated eslint from9.36.0 to9.37.0
- Updated @eslint/js from9.36.0 to 9.37.0
- Updated rollup from 4.52.2 to 4.52.4
- Updated vite from 7.1.7 to7.1.9
- Updated @eslint/core from 0.15.2 to 0.16.0
- Updated @eslint/config-helpers from0.3.1 to0.4.0
- Added @eslint/plugin-kit0.4.0
- Updated all rollup platform-specific packages to4.52.4
- Updated typescript-eslint to use eslint 9.37.0
- Updated unplugin-dts to use rollup4.52.4 and vite7.1.9
=> chore(deps): update eslint and related dependencies to latest versions

packages/react/src/wow/index.ts, packages/react/src/wow/usePagedQuery.ts, packages/react/src/wow/useSingleQuery.ts, packages/react/test/wow/useSingleQuery.test.ts
- Implement useSingleQuery hook with state management for conditions, projections, and sorting
- Add support for executing single queries with async execution
- Include methods to update query parameters (setCondition, setProjection, setSort)
- Extend UseExecutePromiseReturn for consistent promise state handling
- Add comprehensive test coverage for hook functionality and edge cases
- Export useSingleQuery in wow package index for public access
=> feat(react): add useSingleQuery hook for single query management

packages/react/package.json, packages/react/src/wow/index.ts, packages/react/src/wow/useListStreamQuery.ts, packages/react/test/wow/useListStreamQuery.test.ts, pnpm-lock.yaml
- Implemented useListStreamQuery hook with state management for conditions, projections, sorting, and limits
- Added support for executing list stream queries returning ReadableStream of JSON server-sent events
- Included comprehensive test coverage for hook functionality and edge cases
- Updated package dependencies to include @ahoo-wang/fetcher-eventstream
- Added export for new hook in wow module index
=> feat(react): add useListStreamQuery hook for streaming list queries

packages/react/src/wow/useCountQuery.ts, packages/react/src/wow/useListQuery.ts, packages/react/src/wow/useListQueryState.ts, packages/react/src/wow/useListStreamQuery.ts, packages/react/src/wow/usePagedQuery.ts, packages/react/src/wow/useSingleQuery.ts
- Added useMemo to useCountQuery to prevent unnecessary re-renders
- Wrapped return values in useMemo for useListQuery hook
- Optimized useListQueryState with useMemo for better performance
- Applied useMemo to useListStreamQuery return object
- Improved usePagedQuery performance with useMemo optimization
- Enhanced useSingleQuery with useMemo for efficient rendering
=> perf(wow): optimize query hooks with useMemo

packages/react/src/wow/useCountQuery.ts, packages/react/src/wow/useListQuery.ts, packages/react/src/wow/useListStreamQuery.ts, packages/react/src/wow/usePagedQuery.ts, packages/react/src/wow/useSingleQuery.ts
- Added missing error type parameter to UseCountQuery return type
- Updated UseListQuery return type to include error type parameter
- Fixed UseListStreamQuery return type to properly propagate error types
- Corrected UsePagedQuery return type with explicit error type handling
- Enhanced UseSingleQuery return type to support custom error typing
=> fix(types): update generic type parameters in query hooks

packages/react/src/fetcher/useFetcher.ts, packages/react/src/wow/useCountQuery.ts, packages/react/src/wow/useListQuery.ts, packages/react/src/wow/useListStreamQuery.ts, packages/react/src/wow/usePagedQuery.ts, packages/react/src/wow/useSingleQuery.ts
- Import FetcherError from @ahoo-wang/fetcher in all query hooks
- Change default error type from unknown to FetcherError
=> feat(react): use FetcherError as default error type in hooks

pnpm-lock.yaml
- Updated eslint from 9.36.0 to9.37.0
- Updated vite from7.1.7 to 7.1.9
- Updated related dependency versions including: 
- typescript-eslint from 8.45.0(eslint@9.36.0) to8.45.0(eslint@9.37.0)
- eslint-plugin-react-hooks from 5.2.0(eslint@9.36.0) to5.2.0(eslint@9.37.0)
- Removed old eslint and vite version entries
- Updated transitive dependencies to align with new eslint version
- Cleaned up lockfile by removing deprecated dependency entries
=> chore(deps): update eslint and vite dependencies

packages/react/src/wow/useCountQuery.ts, packages/react/src/wow/useListQuery.ts, packages/react/src/wow/useListStreamQuery.ts, packages/react/src/wow/usePagedQuery.ts, packages/react/src/wow/useSingleQuery.ts
- Updated useCountQuery to use UseExecutePromiseOptions
- Updated useListQuery to use UseExecutePromiseOptions
- Updated useListStreamQuery to use UseExecutePromiseOptions
- Updated usePagedQuery to use UseExecutePromiseOptions
- Updated useSingleQuery to use UseExecutePromiseOptions
- Removed deprecated UsePromiseStateOptions import
- Added UseExecutePromiseOptions import where needed
=> refactor(react): replace UsePromiseStateOptions with UseExecutePromiseOptions
